services:

  db:
    container_name: sholatku-db
    image: postgres:18.2-alpine
    environment: 
      POSTGRES_DB: sholatku
      POSTGRES_USER: sholatku
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - "5443:5432"

volumes: 
  db_data: