services:

  pgadmin:
    container_name: sholatku-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@masdepan.my.id
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    networks:
      - sholatku-net

  db:
    container_name: sholatku-db
    image: postgres:18.2-alpine
    environment: 
      POSTGRES_DB: sholatku
      POSTGRES_USER: sholatku
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - ./db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5443:5432"
    networks:
      - sholatku-net

  redis:
    container_name: sholatku-redis
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - sholatku-net

networks:
  sholatku-net:
    name: sholatku-network