CREATE TABLE IF NOT EXISTS locations (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    createdAt   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    province    TEXT NOT NULL,
    city        TEXT NOT NULL,
    CONSTRAINT  locations_province_city_unique UNIQUE (province, city)
);

CREATE TABLE IF NOT EXISTS prayerData (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    createdAt     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    lastUpdatedAt TIMESTAMPTZ DEFAULT NULL,
    locationId    TEXT NOT NULL REFERENCES locations (id)
    prayerTimes  JSON NOT NULL

    CONSTRAINT prayerData_locationId_unique UNIQUE (locationId)
)

CREATE TABLE IF NOT EXISTS prayerStates (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    createdAt     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    lastUpdatedAt TIMESTAMPTZ DEFAULT NULL,
    prayerId      TEXT NOT NULL REFERENCES prayerData (id),
    eventName     TEXT NOT NULL,
    forDate       TIMESTAMPTZ NOT NULL,

    CONSTRAINT prayerStates_prayerId_eventName_forDate_unique UNIQUE (prayerId, eventName, forDate)
)

CREATE TABLE IF NOT EXISTS subscriptions (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    createdAt     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    lastUpdatedAt TIMESTAMPTZ DEFAULT NULL,
    providerName  TEXT NOT NULL,
    metadata      JSON NOT NULL,
)

INSERT INTO locations (province, city) VALUES
  ('Aceh', 'Kab. Aceh Barat'),
  ('Aceh', 'Kab. Aceh Barat Daya'),
  ('Aceh', 'Kab. Aceh Besar'),
  ('Aceh', 'Kab. Aceh Jaya'),
  ('Aceh', 'Kab. Aceh Selatan'),
  ('Aceh', 'Kab. Aceh Singkil'),
  ('Aceh', 'Kab. Aceh Tamiang'),
  ('Aceh', 'Kab. Aceh Tengah'),
  ('Aceh', 'Kab. Aceh Tenggara'),
  ('Aceh', 'Kab. Aceh Timur'),
  ('Aceh', 'Kab. Aceh Utara'),
  ('Aceh', 'Kab. Bener Meriah'),
  ('Aceh', 'Kab. Bireuen'),
  ('Aceh', 'Kab. Gayo Lues'),
  ('Aceh', 'Kab. Nagan Raya'),
  ('Aceh', 'Kab. Pidie'),
  ('Aceh', 'Kab. Pidie Jaya'),
  ('Aceh', 'Kab. Simeulue'),
  ('Aceh', 'Kota Banda Aceh'),
  ('Aceh', 'Kota Langsa'),
  ('Aceh', 'Kota Lhokseumawe'),
  ('Aceh', 'Kota Sabang'),
  ('Aceh', 'Kota Subulussalam'),
  ('Bali', 'Kab. Badung'),
  ('Bali', 'Kab. Bangli'),
  ('Bali', 'Kab. Buleleng'),
  ('Bali', 'Kab. Gianyar'),
  ('Bali', 'Kab. Jembrana'),
  ('Bali', 'Kab. Karangasem'),
  ('Bali', 'Kab. Klungkung'),
  ('Bali', 'Kab. Tabanan'),
  ('Bali', 'Kota Denpasar'),
  ('Banten', 'Kab. Lebak'),
  ('Banten', 'Kab. Pandeglang'),
  ('Banten', 'Kab. Serang'),
  ('Banten', 'Kab. Tangerang'),
  ('Banten', 'Kota Cilegon'),
  ('Banten', 'Kota Serang'),
  ('Banten', 'Kota Tangerang'),
  ('Banten', 'Kota Tangerang Selatan'),
  ('Bengkulu', 'Kab. Bengkulu Selatan'),
  ('Bengkulu', 'Kab. Bengkulu Tengah'),
  ('Bengkulu', 'Kab. Bengkulu Utara'),
  ('Bengkulu', 'Kab. Kaur'),
  ('Bengkulu', 'Kab. Kepahiang'),
  ('Bengkulu', 'Kab. Lebong'),
  ('Bengkulu', 'Kab. Mukomuko'),
  ('Bengkulu', 'Kab. Rejang Lebong'),
  ('Bengkulu', 'Kab. Seluma'),
  ('Bengkulu', 'Kota Bengkulu'),
  ('D_I__Yogyakarta', 'Kab. Bantul'),
  ('D_I__Yogyakarta', 'Kab. Gunungkidul'),
  ('D_I__Yogyakarta', 'Kab. Kulon Progo'),
  ('D_I__Yogyakarta', 'Kab. Sleman'),
  ('D_I__Yogyakarta', 'Kota Yogyakarta'),
  ('DKI_Jakarta', 'Kab. Kepulauan Seribu'),
  ('DKI_Jakarta', 'Kota Jakarta'),
  ('Gorontalo', 'Kab. Boalemo'),
  ('Gorontalo', 'Kab. Bone Bolango'),
  ('Gorontalo', 'Kab. Gorontalo'),
  ('Gorontalo', 'Kab. Gorontalo Utara'),
  ('Gorontalo', 'Kab. Pahuwato'),
  ('Gorontalo', 'Kota Gorontalo'),
  ('Jambi', 'Kab. Batanghari'),
  ('Jambi', 'Kab. Bungo'),
  ('Jambi', 'Kab. Kerinci'),
  ('Jambi', 'Kab. Merangin'),
  ('Jambi', 'Kab. Muaro Jambi'),
  ('Jambi', 'Kab. Sarolangun'),
  ('Jambi', 'Kab. Tanjung Jabung Barat'),
  ('Jambi', 'Kab. Tanjung Jabung Timur'),
  ('Jambi', 'Kab. Tebo'),
  ('Jambi', 'Kota Jambi'),
  ('Jambi', 'Kota Sungai Penuh'),
  ('Jawa_Barat', 'Kab. Bandung'),
  ('Jawa_Barat', 'Kab. Bandung Barat'),
  ('Jawa_Barat', 'Kab. Bekasi'),
  ('Jawa_Barat', 'Kab. Bogor'),
  ('Jawa_Barat', 'Kab. Ciamis'),
  ('Jawa_Barat', 'Kab. Cianjur'),
  ('Jawa_Barat', 'Kab. Cirebon'),
  ('Jawa_Barat', 'Kab. Garut'),
  ('Jawa_Barat', 'Kab. Indramayu'),
  ('Jawa_Barat', 'Kab. Karawang'),
  ('Jawa_Barat', 'Kab. Kuningan'),
  ('Jawa_Barat', 'Kab. Majalengka'),
  ('Jawa_Barat', 'Kab. Pangandaran'),
  ('Jawa_Barat', 'Kab. Purwakarta'),
  ('Jawa_Barat', 'Kab. Subang'),
  ('Jawa_Barat', 'Kab. Sukabumi'),
  ('Jawa_Barat', 'Kab. Sumedang'),
  ('Jawa_Barat', 'Kab. Tasikmalaya'),
  ('Jawa_Barat', 'Kota Bandung'),
  ('Jawa_Barat', 'Kota Banjar'),
  ('Jawa_Barat', 'Kota Bekasi'),
  ('Jawa_Barat', 'Kota Bogor'),
  ('Jawa_Barat', 'Kota Cimahi'),
  ('Jawa_Barat', 'Kota Cirebon'),
  ('Jawa_Barat', 'Kota Depok'),
  ('Jawa_Barat', 'Kota Sukabumi'),
  ('Jawa_Barat', 'Kota Tasikmalaya'),
  ('Jawa_Tengah', 'Kab. Banjarnegara'),
  ('Jawa_Tengah', 'Kab. Banyumas'),
  ('Jawa_Tengah', 'Kab. Batang'),
  ('Jawa_Tengah', 'Kab. Blora'),
  ('Jawa_Tengah', 'Kab. Boyolali'),
  ('Jawa_Tengah', 'Kab. Brebes'),
  ('Jawa_Tengah', 'Kab. Cilacap'),
  ('Jawa_Tengah', 'Kab. Demak'),
  ('Jawa_Tengah', 'Kab. Grobogan'),
  ('Jawa_Tengah', 'Kab. Jepara'),
  ('Jawa_Tengah', 'Kab. Karanganyar'),
  ('Jawa_Tengah', 'Kab. Kebumen'),
  ('Jawa_Tengah', 'Kab. Kendal'),
  ('Jawa_Tengah', 'Kab. Klaten'),
  ('Jawa_Tengah', 'Kab. Kudus'),
  ('Jawa_Tengah', 'Kab. Magelang'),
  ('Jawa_Tengah', 'Kab. Pati'),
  ('Jawa_Tengah', 'Kab. Pekalongan'),
  ('Jawa_Tengah', 'Kab. Pemalang'),
  ('Jawa_Tengah', 'Kab. Purbalingga'),
  ('Jawa_Tengah', 'Kab. Purworejo'),
  ('Jawa_Tengah', 'Kab. Rembang'),
  ('Jawa_Tengah', 'Kab. Semarang'),
  ('Jawa_Tengah', 'Kab. Sragen'),
  ('Jawa_Tengah', 'Kab. Sukoharjo'),
  ('Jawa_Tengah', 'Kab. Tegal'),
  ('Jawa_Tengah', 'Kab. Temanggung'),
  ('Jawa_Tengah', 'Kab. Wonogiri'),
  ('Jawa_Tengah', 'Kab. Wonosobo'),
  ('Jawa_Tengah', 'Kota Magelang'),
  ('Jawa_Tengah', 'Kota Pekalongan'),
  ('Jawa_Tengah', 'Kota Salatiga'),
  ('Jawa_Tengah', 'Kota Semarang'),
  ('Jawa_Tengah', 'Kota Surakarta'),
  ('Jawa_Tengah', 'Kota Tegal'),
  ('Jawa_Timur', 'Kab. Bangkalan'),
  ('Jawa_Timur', 'Kab. Banyuwangi'),
  ('Jawa_Timur', 'Kab. Blitar'),
  ('Jawa_Timur', 'Kab. Bojonegoro'),
  ('Jawa_Timur', 'Kab. Bondowoso'),
  ('Jawa_Timur', 'Kab. Gresik'),
  ('Jawa_Timur', 'Kab. Jember'),
  ('Jawa_Timur', 'Kab. Jombang'),
  ('Jawa_Timur', 'Kab. Kediri'),
  ('Jawa_Timur', 'Kab. Lamongan'),
  ('Jawa_Timur', 'Kab. Lumajang'),
  ('Jawa_Timur', 'Kab. Madiun'),
  ('Jawa_Timur', 'Kab. Magetan'),
  ('Jawa_Timur', 'Kab. Malang'),
  ('Jawa_Timur', 'Kab. Mojokerto'),
  ('Jawa_Timur', 'Kab. Nganjuk'),
  ('Jawa_Timur', 'Kab. Ngawi'),
  ('Jawa_Timur', 'Kab. Pacitan'),
  ('Jawa_Timur', 'Kab. Pamekasan'),
  ('Jawa_Timur', 'Kab. Pasuruan'),
  ('Jawa_Timur', 'Kab. Ponorogo'),
  ('Jawa_Timur', 'Kab. Probolinggo'),
  ('Jawa_Timur', 'Kab. Sampang'),
  ('Jawa_Timur', 'Kab. Sidoarjo'),
  ('Jawa_Timur', 'Kab. Situbondo'),
  ('Jawa_Timur', 'Kab. Sumenep'),
  ('Jawa_Timur', 'Kab. Trenggalek'),
  ('Jawa_Timur', 'Kab. Tuban'),
  ('Jawa_Timur', 'Kab. Tulungagung'),
  ('Jawa_Timur', 'Kota Batu'),
  ('Jawa_Timur', 'Kota Blitar'),
  ('Jawa_Timur', 'Kota Kediri'),
  ('Jawa_Timur', 'Kota Madiun'),
  ('Jawa_Timur', 'Kota Malang'),
  ('Jawa_Timur', 'Kota Mojokerto'),
  ('Jawa_Timur', 'Kota Pasuruan'),
  ('Jawa_Timur', 'Kota Probolinggo'),
  ('Jawa_Timur', 'Kota Surabaya'),
  ('Kalimantan_Barat', 'Kab. Bengkayang'),
  ('Kalimantan_Barat', 'Kab. Kapuas Hulu'),
  ('Kalimantan_Barat', 'Kab. Kayong Utara'),
  ('Kalimantan_Barat', 'Kab. Ketapang'),
  ('Kalimantan_Barat', 'Kab. Kubu Raya'),
  ('Kalimantan_Barat', 'Kab. Landak'),
  ('Kalimantan_Barat', 'Kab. Melawi'),
  ('Kalimantan_Barat', 'Kab. Mempawah'),
  ('Kalimantan_Barat', 'Kab. Sambas'),
  ('Kalimantan_Barat', 'Kab. Sanggau'),
  ('Kalimantan_Barat', 'Kab. Sekadau'),
  ('Kalimantan_Barat', 'Kab. Sintang'),
  ('Kalimantan_Barat', 'Kota Pontianak'),
  ('Kalimantan_Barat', 'Kota Singkawang'),
  ('Kalimantan_Selatan', 'Kab. Balangan'),
  ('Kalimantan_Selatan', 'Kab. Banjar'),
  ('Kalimantan_Selatan', 'Kab. Barito Kuala'),
  ('Kalimantan_Selatan', 'Kab. Hulu Sungai Selatan'),
  ('Kalimantan_Selatan', 'Kab. Hulu Sungai Tengah'),
  ('Kalimantan_Selatan', 'Kab. Hulu Sungai Utara'),
  ('Kalimantan_Selatan', 'Kab. Kotabaru'),
  ('Kalimantan_Selatan', 'Kab. Tabalong'),
  ('Kalimantan_Selatan', 'Kab. Tanah Bumbu'),
  ('Kalimantan_Selatan', 'Kab. Tanah Laut'),
  ('Kalimantan_Selatan', 'Kab. Tapin'),
  ('Kalimantan_Selatan', 'Kota Banjarbaru'),
  ('Kalimantan_Selatan', 'Kota Banjarmasin'),
  ('Kalimantan_Tengah', 'Kab. Barito Selatan'),
  ('Kalimantan_Tengah', 'Kab. Barito Timur'),
  ('Kalimantan_Tengah', 'Kab. Barito Utara'),
  ('Kalimantan_Tengah', 'Kab. Gunung Mas'),
  ('Kalimantan_Tengah', 'Kab. Kapuas'),
  ('Kalimantan_Tengah', 'Kab. Katingan'),
  ('Kalimantan_Tengah', 'Kab. Kotawaringin Barat'),
  ('Kalimantan_Tengah', 'Kab. Kotawaringin Timur'),
  ('Kalimantan_Tengah', 'Kab. Lamandau'),
  ('Kalimantan_Tengah', 'Kab. Murung Raya'),
  ('Kalimantan_Tengah', 'Kab. Pulang Pisau'),
  ('Kalimantan_Tengah', 'Kab. Seruyan'),
  ('Kalimantan_Tengah', 'Kab. Sukamara'),
  ('Kalimantan_Tengah', 'Kota Palangkaraya'),
  ('Kalimantan_Timur', 'Kab. Berau'),
  ('Kalimantan_Timur', 'Kab. Kutai Barat'),
  ('Kalimantan_Timur', 'Kab. Kutai Kartanegara'),
  ('Kalimantan_Timur', 'Kab. Kutai Timur'),
  ('Kalimantan_Timur', 'Kab. Mahakam ULU'),
  ('Kalimantan_Timur', 'Kab. Paser'),
  ('Kalimantan_Timur', 'Kab. Penajam Paser Utara'),
  ('Kalimantan_Timur', 'Kota Balikpapan'),
  ('Kalimantan_Timur', 'Kota Bontang'),
  ('Kalimantan_Timur', 'Kota Samarinda'),
  ('Kalimantan_Utara', 'Kab. Bulungan'),
  ('Kalimantan_Utara', 'Kab. Malinau'),
  ('Kalimantan_Utara', 'Kab. Nunukan'),
  ('Kalimantan_Utara', 'Kab. Tana Tidung'),
  ('Kalimantan_Utara', 'Kota Tarakan'),
  ('Kepulauan_Bangka_Belitung', 'Kab. Bangka'),
  ('Kepulauan_Bangka_Belitung', 'Kab. Bangka Barat'),
  ('Kepulauan_Bangka_Belitung', 'Kab. Bangka Selatan'),
  ('Kepulauan_Bangka_Belitung', 'Kab. Bangka Tengah'),
  ('Kepulauan_Bangka_Belitung', 'Kab. Belitung'),
  ('Kepulauan_Bangka_Belitung', 'Kab. Belitung Timur'),
  ('Kepulauan_Bangka_Belitung', 'Kota Pangkal Pinang'),
  ('Kepulauan_Riau', 'Kab. Bintan'),
  ('Kepulauan_Riau', 'Kab. Karimun'),
  ('Kepulauan_Riau', 'Kab. Kepulauan Anambas'),
  ('Kepulauan_Riau', 'Kab. Lingga'),
  ('Kepulauan_Riau', 'Kab. Natuna'),
  ('Kepulauan_Riau', 'Kota Batam'),
  ('Kepulauan_Riau', 'Kota Tanjung Pinang'),
  ('Kepulauan_Riau', 'Pekajang Kab. Lingga'),
  ('Kepulauan_Riau', 'Pulau Laut Kab. Natuna'),
  ('Kepulauan_Riau', 'Pulau Midai Kab. Natuna'),
  ('Kepulauan_Riau', 'Pulau Serasan Kab. Natuna'),
  ('Kepulauan_Riau', 'Pulau Tambelan Kab. Bintan'),
  ('Lampung', 'Kab. Lampung Barat'),
  ('Lampung', 'Kab. Lampung Selatan'),
  ('Lampung', 'Kab. Lampung Tengah'),
  ('Lampung', 'Kab. Lampung Timur'),
  ('Lampung', 'Kab. Lampung Utara'),
  ('Lampung', 'Kab. Mesuji'),
  ('Lampung', 'Kab. Pesawaran'),
  ('Lampung', 'Kab. Pesisir Barat'),
  ('Lampung', 'Kab. Pringsewu'),
  ('Lampung', 'Kab. Tanggamus'),
  ('Lampung', 'Kab. Tulang Bawang'),
  ('Lampung', 'Kab. Tulang Bawang Barat'),
  ('Lampung', 'Kab. Way Kanan'),
  ('Lampung', 'Kota Bandar Lampung'),
  ('Lampung', 'Kota Metro'),
  ('Maluku', 'Kab. Buru'),
  ('Maluku', 'Kab. Buru Selatan'),
  ('Maluku', 'Kab. Kepulauan Aru'),
  ('Maluku', 'Kab. Maluku Barat Daya'),
  ('Maluku', 'Kab. Maluku Tengah'),
  ('Maluku', 'Kab. Maluku Tenggara'),
  ('Maluku', 'Kab. Maluku Tenggara Barat'),
  ('Maluku', 'Kab. Seram Bagian Barat'),
  ('Maluku', 'Kab. Seram Bagian Timur'),
  ('Maluku', 'Kota Ambon'),
  ('Maluku', 'Kota Tual'),
  ('Maluku_Utara', 'Kab. Halmahera Barat'),
  ('Maluku_Utara', 'Kab. Halmahera Selatan'),
  ('Maluku_Utara', 'Kab. Halmahera Tengah'),
  ('Maluku_Utara', 'Kab. Halmahera Timur'),
  ('Maluku_Utara', 'Kab. Halmahera Utara'),
  ('Maluku_Utara', 'Kab. Kepulauan Sula'),
  ('Maluku_Utara', 'Kab. Pulau Morotai'),
  ('Maluku_Utara', 'Kab. Pulau Taliabu'),
  ('Maluku_Utara', 'Kota Sofifi'),
  ('Maluku_Utara', 'Kota Ternate'),
  ('Maluku_Utara', 'Kota Tidore Kepulauan'),
  ('Nusa_Tenggara_Barat', 'Kab. Bima'),
  ('Nusa_Tenggara_Barat', 'Kab. Dompu'),
  ('Nusa_Tenggara_Barat', 'Kab. Lombok Barat'),
  ('Nusa_Tenggara_Barat', 'Kab. Lombok Tengah'),
  ('Nusa_Tenggara_Barat', 'Kab. Lombok Timur'),
  ('Nusa_Tenggara_Barat', 'Kab. Lombok Utara'),
  ('Nusa_Tenggara_Barat', 'Kab. Sumbawa'),
  ('Nusa_Tenggara_Barat', 'Kab. Sumbawa Barat'),
  ('Nusa_Tenggara_Barat', 'Kota Bima'),
  ('Nusa_Tenggara_Barat', 'Kota Mataram'),
  ('Nusa_Tenggara_Timur', 'Kab. Alor'),
  ('Nusa_Tenggara_Timur', 'Kab. Belu'),
  ('Nusa_Tenggara_Timur', 'Kab. Ende'),
  ('Nusa_Tenggara_Timur', 'Kab. Flores Timur'),
  ('Nusa_Tenggara_Timur', 'Kab. Kupang'),
  ('Nusa_Tenggara_Timur', 'Kab. Lembata'),
  ('Nusa_Tenggara_Timur', 'Kab. Malaka'),
  ('Nusa_Tenggara_Timur', 'Kab. Manggarai'),
  ('Nusa_Tenggara_Timur', 'Kab. Manggarai Barat'),
  ('Nusa_Tenggara_Timur', 'Kab. Manggarai Timur'),
  ('Nusa_Tenggara_Timur', 'Kab. Nagekeo'),
  ('Nusa_Tenggara_Timur', 'Kab. Ngada'),
  ('Nusa_Tenggara_Timur', 'Kab. Rote Ndao'),
  ('Nusa_Tenggara_Timur', 'Kab. Sabu Raijua'),
  ('Nusa_Tenggara_Timur', 'Kab. Sikka'),
  ('Nusa_Tenggara_Timur', 'Kab. Sumba Barat'),
  ('Nusa_Tenggara_Timur', 'Kab. Sumba Barat Daya'),
  ('Nusa_Tenggara_Timur', 'Kab. Sumba Tengah'),
  ('Nusa_Tenggara_Timur', 'Kab. Sumba Timur'),
  ('Nusa_Tenggara_Timur', 'Kab. Timor Tengah Selatan'),
  ('Nusa_Tenggara_Timur', 'Kab. Timor Tengah Utara'),
  ('Nusa_Tenggara_Timur', 'Kota Kupang'),
  ('Papua', 'Kab. Asmat'),
  ('Papua', 'Kab. Biak Numfor'),
  ('Papua', 'Kab. Boven Digoel'),
  ('Papua', 'Kab. Deiyai'),
  ('Papua', 'Kab. Dogiyai'),
  ('Papua', 'Kab. Intan Jaya'),
  ('Papua', 'Kab. Jayapura'),
  ('Papua', 'Kab. Jayawijaya'),
  ('Papua', 'Kab. Keerom'),
  ('Papua', 'Kab. Kepulauan Yapen'),
  ('Papua', 'Kab. Lanny Jaya'),
  ('Papua', 'Kab. Mamberamo Raya'),
  ('Papua', 'Kab. Mamberamo Tengah'),
  ('Papua', 'Kab. Mappi'),
  ('Papua', 'Kab. Merauke'),
  ('Papua', 'Kab. Mimika'),
  ('Papua', 'Kab. Nabire'),
  ('Papua', 'Kab. Nduga'),
  ('Papua', 'Kab. Paniai'),
  ('Papua', 'Kab. Pegunungan Bintang'),
  ('Papua', 'Kab. Puncak'),
  ('Papua', 'Kab. Puncak Jaya'),
  ('Papua', 'Kab. Sarmi'),
  ('Papua', 'Kab. Supiori'),
  ('Papua', 'Kab. Tolikara'),
  ('Papua', 'Kab. Waropen'),
  ('Papua', 'Kab. Yahukimo'),
  ('Papua', 'Kab. Yalimo'),
  ('Papua', 'Kab. Yapen Waropen'),
  ('Papua', 'Kota Jayapura'),
  ('Papua_Barat', 'Kab. Fakfak'),
  ('Papua_Barat', 'Kab. Kaimana'),
  ('Papua_Barat', 'Kab. Manokwari'),
  ('Papua_Barat', 'Kab. Manokwari Selatan'),
  ('Papua_Barat', 'Kab. Maybrat'),
  ('Papua_Barat', 'Kab. Pegunungan Arfak'),
  ('Papua_Barat', 'Kab. Raja Ampat'),
  ('Papua_Barat', 'Kab. Sorong'),
  ('Papua_Barat', 'Kab. Sorong Selatan'),
  ('Papua_Barat', 'Kab. Tambrauw'),
  ('Papua_Barat', 'Kab. Teluk Bintuni'),
  ('Papua_Barat', 'Kab. Teluk Wondama'),
  ('Papua_Barat', 'Kota Sorong'),
  ('Riau', 'Kab. Bengkalis'),
  ('Riau', 'Kab. Indragiri Hilir'),
  ('Riau', 'Kab. Indragiri Hulu'),
  ('Riau', 'Kab. Kampar'),
  ('Riau', 'Kab. Kepulauan Meranti'),
  ('Riau', 'Kab. Kuantan Singingi'),
  ('Riau', 'Kab. Pelalawan'),
  ('Riau', 'Kab. Rokan Hilir'),
  ('Riau', 'Kab. Rokan Hulu'),
  ('Riau', 'Kab. Siak'),
  ('Riau', 'Kota Dumai'),
  ('Riau', 'Kota Pekanbaru'),
  ('Sulawesi_Barat', 'Kab. Majene'),
  ('Sulawesi_Barat', 'Kab. Mamasa'),
  ('Sulawesi_Barat', 'Kab. Mamuju'),
  ('Sulawesi_Barat', 'Kab. Mamuju Tengah'),
  ('Sulawesi_Barat', 'Kab. Mamuju Utara'),
  ('Sulawesi_Barat', 'Kab. Polewali Mandar'),
  ('Sulawesi_Selatan', 'Kab. Bantaeng'),
  ('Sulawesi_Selatan', 'Kab. Barru'),
  ('Sulawesi_Selatan', 'Kab. Bone'),
  ('Sulawesi_Selatan', 'Kab. Bulukumba'),
  ('Sulawesi_Selatan', 'Kab. Enrekang'),
  ('Sulawesi_Selatan', 'Kab. Gowa'),
  ('Sulawesi_Selatan', 'Kab. Jeneponto'),
  ('Sulawesi_Selatan', 'Kab. Kepulauan Selayar'),
  ('Sulawesi_Selatan', 'Kab. Luwu'),
  ('Sulawesi_Selatan', 'Kab. Luwu Timur'),
  ('Sulawesi_Selatan', 'Kab. Luwu Utara'),
  ('Sulawesi_Selatan', 'Kab. Maros'),
  ('Sulawesi_Selatan', 'Kab. Pangkajene Dan Kepulauan'),
  ('Sulawesi_Selatan', 'Kab. Pinrang'),
  ('Sulawesi_Selatan', 'Kab. Sidenreng Rappang'),
  ('Sulawesi_Selatan', 'Kab. Sinjai'),
  ('Sulawesi_Selatan', 'Kab. Soppeng'),
  ('Sulawesi_Selatan', 'Kab. Takalar'),
  ('Sulawesi_Selatan', 'Kab. Tana Toraja'),
  ('Sulawesi_Selatan', 'Kab. Toraja Utara'),
  ('Sulawesi_Selatan', 'Kab. Wajo'),
  ('Sulawesi_Selatan', 'Kota Makassar'),
  ('Sulawesi_Selatan', 'Kota Palopo'),
  ('Sulawesi_Selatan', 'Kota Parepare'),
  ('Sulawesi_Tengah', 'Kab. Banggai'),
  ('Sulawesi_Tengah', 'Kab. Banggai Kepulauan'),
  ('Sulawesi_Tengah', 'Kab. Banggai Laut'),
  ('Sulawesi_Tengah', 'Kab. Buol'),
  ('Sulawesi_Tengah', 'Kab. Donggala'),
  ('Sulawesi_Tengah', 'Kab. Morowali'),
  ('Sulawesi_Tengah', 'Kab. Morowali Utara'),
  ('Sulawesi_Tengah', 'Kab. Parigi Moutong'),
  ('Sulawesi_Tengah', 'Kab. Poso'),
  ('Sulawesi_Tengah', 'Kab. Sigi'),
  ('Sulawesi_Tengah', 'Kab. Tojo UNA-UNA'),
  ('Sulawesi_Tengah', 'Kab. Toli-Toli'),
  ('Sulawesi_Tengah', 'Kota Palu'),
  ('Sulawesi_Tenggara', 'Kab. Bombana'),
  ('Sulawesi_Tenggara', 'Kab. Buton'),
  ('Sulawesi_Tenggara', 'Kab. Buton Selatan'),
  ('Sulawesi_Tenggara', 'Kab. Buton Tengah'),
  ('Sulawesi_Tenggara', 'Kab. Buton Utara'),
  ('Sulawesi_Tenggara', 'Kab. Kolaka'),
  ('Sulawesi_Tenggara', 'Kab. Kolaka Timur'),
  ('Sulawesi_Tenggara', 'Kab. Kolaka Utara'),
  ('Sulawesi_Tenggara', 'Kab. Konawe'),
  ('Sulawesi_Tenggara', 'Kab. Konawe Kepulauan'),
  ('Sulawesi_Tenggara', 'Kab. Konawe Selatan'),
  ('Sulawesi_Tenggara', 'Kab. Konawe Utara'),
  ('Sulawesi_Tenggara', 'Kab. Muna'),
  ('Sulawesi_Tenggara', 'Kab. Muna Barat'),
  ('Sulawesi_Tenggara', 'Kab. Wakatobi'),
  ('Sulawesi_Tenggara', 'Kota Bau-Bau'),
  ('Sulawesi_Tenggara', 'Kota Kendari'),
  ('Sulawesi_Utara', 'Kab. Bolaang Mongondow'),
  ('Sulawesi_Utara', 'Kab. Bolaang Mongondow Selatan'),
  ('Sulawesi_Utara', 'Kab. Bolaang Mongondow Timur'),
  ('Sulawesi_Utara', 'Kab. Bolaang Mongondow Utara'),
  ('Sulawesi_Utara', 'Kab. Kepulauan Sangihe'),
  ('Sulawesi_Utara', 'Kab. Kepulauan Siau Tagulandang Biaro'),
  ('Sulawesi_Utara', 'Kab. Kepulauan Talaud'),
  ('Sulawesi_Utara', 'Kab. Minahasa'),
  ('Sulawesi_Utara', 'Kab. Minahasa Selatan'),
  ('Sulawesi_Utara', 'Kab. Minahasa Tenggara'),
  ('Sulawesi_Utara', 'Kab. Minahasa Utara'),
  ('Sulawesi_Utara', 'Kota Bitung'),
  ('Sulawesi_Utara', 'Kota Kotamobagu'),
  ('Sulawesi_Utara', 'Kota Manado'),
  ('Sulawesi_Utara', 'Kota Tomohon'),
  ('Sumatera_Barat', 'Kab. Agam'),
  ('Sumatera_Barat', 'Kab. Dharmasraya'),
  ('Sumatera_Barat', 'Kab. Kepulauan Mentawai'),
  ('Sumatera_Barat', 'Kab. Lima Puluh Kota'),
  ('Sumatera_Barat', 'Kab. Padang Pariaman'),
  ('Sumatera_Barat', 'Kab. Pasaman'),
  ('Sumatera_Barat', 'Kab. Pasaman Barat'),
  ('Sumatera_Barat', 'Kab. Pesisir Selatan'),
  ('Sumatera_Barat', 'Kab. Sijunjung'),
  ('Sumatera_Barat', 'Kab. Solok'),
  ('Sumatera_Barat', 'Kab. Solok Selatan'),
  ('Sumatera_Barat', 'Kab. Tanah Datar'),
  ('Sumatera_Barat', 'Kota Bukittinggi'),
  ('Sumatera_Barat', 'Kota Padang'),
  ('Sumatera_Barat', 'Kota Padangpanjang'),
  ('Sumatera_Barat', 'Kota Pariaman'),
  ('Sumatera_Barat', 'Kota Payakumbuh'),
  ('Sumatera_Barat', 'Kota Sawahlunto'),
  ('Sumatera_Barat', 'Kota Solok'),
  ('Sumatera_Selatan', 'Kab. Banyuasin'),
  ('Sumatera_Selatan', 'Kab. Empat Lawang'),
  ('Sumatera_Selatan', 'Kab. Lahat'),
  ('Sumatera_Selatan', 'Kab. Muara Enim'),
  ('Sumatera_Selatan', 'Kab. Musi Banyuasin'),
  ('Sumatera_Selatan', 'Kab. Musi Rawas'),
  ('Sumatera_Selatan', 'Kab. Musi Rawas Utara'),
  ('Sumatera_Selatan', 'Kab. Ogan ILIR'),
  ('Sumatera_Selatan', 'Kab. Ogan Komering ILIR'),
  ('Sumatera_Selatan', 'Kab. Ogan Komering ULU'),
  ('Sumatera_Selatan', 'Kab. Ogan Komering ULU Selatan'),
  ('Sumatera_Selatan', 'Kab. Ogan Komering ULU Timur'),
  ('Sumatera_Selatan', 'Kab. Penukal Abab Lematang ILIR'),
  ('Sumatera_Selatan', 'Kota Lubuklinggau'),
  ('Sumatera_Selatan', 'Kota Pagar Alam'),
  ('Sumatera_Selatan', 'Kota Palembang'),
  ('Sumatera_Selatan', 'Kota Prabumulih'),
  ('Sumatera_Utara', 'Kab. Asahan'),
  ('Sumatera_Utara', 'Kab. Batu Bara'),
  ('Sumatera_Utara', 'Kab. Dairi'),
  ('Sumatera_Utara', 'Kab. Deli Serdang'),
  ('Sumatera_Utara', 'Kab. Humbang Hasundutan'),
  ('Sumatera_Utara', 'Kab. Karo'),
  ('Sumatera_Utara', 'Kab. Labuhanbatu'),
  ('Sumatera_Utara', 'Kab. Labuhanbatu Selatan'),
  ('Sumatera_Utara', 'Kab. Labuhanbatu Utara'),
  ('Sumatera_Utara', 'Kab. Langkat'),
  ('Sumatera_Utara', 'Kab. Mandailing Natal'),
  ('Sumatera_Utara', 'Kab. Nias'),
  ('Sumatera_Utara', 'Kab. Nias Barat'),
  ('Sumatera_Utara', 'Kab. Nias Selatan'),
  ('Sumatera_Utara', 'Kab. Nias Utara'),
  ('Sumatera_Utara', 'Kab. Padang Lawas'),
  ('Sumatera_Utara', 'Kab. Padang Lawas Utara'),
  ('Sumatera_Utara', 'Kab. Pakpak Bharat'),
  ('Sumatera_Utara', 'Kab. Samosir'),
  ('Sumatera_Utara', 'Kab. Serdang Bedagai'),
  ('Sumatera_Utara', 'Kab. Simalungun'),
  ('Sumatera_Utara', 'Kab. Tapanuli Selatan'),
  ('Sumatera_Utara', 'Kab. Tapanuli Tengah'),
  ('Sumatera_Utara', 'Kab. Tapanuli Utara'),
  ('Sumatera_Utara', 'Kab. Toba Samosir'),
  ('Sumatera_Utara', 'Kota Binjai'),
  ('Sumatera_Utara', 'Kota Gunungsitoli'),
  ('Sumatera_Utara', 'Kota Medan'),
  ('Sumatera_Utara', 'Kota Padangsidempuan'),
  ('Sumatera_Utara', 'Kota Pematangsiantar'),
  ('Sumatera_Utara', 'Kota Sibolga'),
  ('Sumatera_Utara', 'Kota Tanjungbalai'),
  ('Sumatera_Utara', 'Kota Tebing Tinggi');
