name: Sholatku CI

on:
    push:
        branches: [ main, dev ]
    pull_request:
        branches: [ main, dev ]

jobs:
    linting-core:
      runs-on: ubuntu-latest

      steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: "NPM CI Thingy"
        run: npm ci

      - name: "Lint - Check for errors & unused vars on package core"
        run: npm run lint-core

    linting-discord:
      runs-on: ubuntu-latest

      steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: "NPM CI Thingy"
        run: npm ci

      - name: "Lint - Check for errors & unused vars on package discord"
        run: npm run lint-discord

    linting-whatsapp:
      runs-on: ubuntu-latest

      steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: "NPM CI Thingy"
        run: npm ci

      - name: "Lint - Check for errors & unused vars on package whatsapp"
        run: npm run lint-whatsapp